created a navbar and heroComponenet
salafidevelopers/shaikhnahari pull request #2
Opened 2024-03-28 07:53 UTC by iamluqmaan

## List of changes
_Provide an overview_

## Screenshots
_Add before change and after change if it has been worked on previously_

## Steps on how to test it
_For example_
- Navigate to `/home` page
- Click on the about button
- It naviagtes to the `/about` page

2024-03-28 07:55 UTC, iamluqmaan commented
I'm not done working on the hover states of the navbar but that's what I've covered so far.

2024-03-28 08:24 UTC, AOMuiz requested changes

2024-03-28 08:24 UTC, AOMuiz commented on package.json
you shouldn't install any external package and if necessary consult first if its what we need.

2024-03-28 08:24 UTC, AOMuiz commented on src/components/navbar.tsx
> +// import {ChevronDown, Lock, Activity, Flash, Server, TagUser, Scale} from "./Icons.jsx";
make sure to remove any unused code when done.

2024-03-28 08:24 UTC, AOMuiz commented on tailwind.config.ts
> +    plugins: [nextui()],
remove code.

2024-03-31 05:22 UTC, AOMuiz approved these changes

2024-03-31 05:23 UTC, merged