audio-recitation-page  pull
salafidevelopers/shaikhnahari pull request #3
Opened 2024-04-16 09:24 UTC by iamluqmaan

## List of changes
_Provide an overview_

## Screenshots
_Add before change and after change if it has been worked on previously_

## Steps on how to test it
_For example_
- Navigate to `/home` page
- Click on the about button
- It naviagtes to the `/about` page

2024-04-16 09:25 UTC, iamluqmaan commented
audio is still ongoing will be be completed inshallah by today

2024-04-17 17:43 UTC, AOMuiz requested changes

2024-04-17 17:43 UTC, AOMuiz commented on src/components/AudioRecitationCard.tsx
> +                  <span className='md:text-sm text-xs'> Twitter </span>
please take note of the actual color of different texts in the ui, usually all text will appear white if you are on dark mode in your system so you wouldn't notice it. i corrected something similar in the first task as well.

2024-04-17 17:43 UTC, AOMuiz commented on src/components/AudioRecitationCard.tsx
> +      {/* second group */}
also instead of making copy and pasting the actual code just create an array and map through to it for each audio card in the ui.

2024-04-17 17:43 UTC, AOMuiz commented on src/components/AudioRecitationCard.tsx
> +export default function AudioRecitationCard() {
the audio card component should only include te neceesaary code for a singlle instance of it, other shoukld be through mapping and props for the correct data.

2024-04-17 17:43 UTC, AOMuiz commented on src/pages/AudioRecitations.tsx
> +          <AudioRecitationCard />
this is where the mapping of the single audio card should be

2024-04-22 17:34 UTC, closed without merging